# Generated by Django 5.1.6 on 2025-03-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofiles_groups_userprofiles_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
