# Generated by Django 5.1.6 on 2025-03-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofiles_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
