# Generated by Django 5.1.6 on 2025-03-25 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofiles_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='datetime_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
