# Generated by Django 5.1.6 on 2025-03-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofiles_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='FirstName',
            field=models.CharField(max_length=250),
        ),
    ]
