# Generated by Django 5.1.6 on 2025-04-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofiles_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='LastName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
