# Generated by Django 5.1.6 on 2025-04-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofiles_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
