# Generated by Django 5.1.6 on 2025-03-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_like_unique_together_like_unique_like'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like',
        ),
    ]
